inherit_from: .rubocop_todo.yml

require: rubocop-performance
AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  SuggestExtensions: false
Style/Documentation:
  Exclude:
    - "spec/**/*"
    - "lib/openapi_first/response_validation/validators/*.rb"
    - "benchmarks/**/*"
    - "lib/openapi_first/json_refs.rb"
    - "lib/openapi_first/request_validation/validators/*.rb"
Style/ExponentialNotation:
  Enabled: true
Style/MapIntoArray:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "*.gemspec"
Layout/LineLength:
  Exclude:
    - "spec/**/*.rb"
Metrics/MethodLength:
  Max: 20
